name: Build

on: [push, pull_request]

jobs:
  build-os-wheel:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]

    steps:
      - uses: actions/checkout@v4
      - uses: robinraju/release-downloader@v1.9
        with:
          repository: "fixstars/ion-kit"
          latest: true
          fileName: "*"
      
      - name: Copy file
        run: |
          mkdir $GITHUB_WORKSPACE/macos
          tar xzf  ion-kit-*macos.tar.gz  -C $GITHUB_WORKSPACE/macos --strip-components 1
          cp  $GITHUB_WORKSPACE/macos/lib/libHalide.16.0.0.dylib python/ionpy/module/macos/libHalide.16.dylib
          cp  $GITHUB_WORKSPACE/macos/lib/libion-core.dylib python/ionpy/module/macos/libion-core.dylib
          cp  $GITHUB_WORKSPACE/macos/lib/libion-bb.dylib python/ionpy/module/macos/libion-bb.dylib
          ls python/ionpy/module/macos
      # Used to host cibuildwheel
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.4
      
      - name: Build wheels
        run: |
          cd python && python -m cibuildwheel --output-dir wheelhouse && ls
        env:
          CIBW_ARCHS_MACOS: auto universal2
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
      
      - name: check
        run: |
           cd python/wheelhouse && ls 
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: python/wheelhouse/*.whl
  
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: cd python && pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: python/dist/*.tar.gz
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value
