# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push
jobs:


   
  test_TEST_PYPI1:
    name: Test wheels on macos
    runs-on: flyci-macos-large-latest-m1

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: x64
     
      - name: test
        run: 
        

          pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple ion-python==0.2.1
          python -c "import ionpy"

      
        
